version: '3.8'

services:
  etcd-s1:
    image: quay.io/coreos/etcd:v3.5.14
    entrypoint:
      [
        "/usr/local/bin/etcd",
        "--config-file",
        "/tmp/etcd/config/etcd.conf.yml"
      ]
    ports:
      - "23791:2379"
    environment:
      ETCDCTL_API: 3
    volumes:
      - type: bind
        source: /data/containers/etcd/s1
        target: /tmp/etcd
    networks:
      etcd-net:
        ipv4_address: ETCD_IPV4_S1

  etcd-s2:
    image: quay.io/coreos/etcd:v3.5.14
    entrypoint:
      [
        "/usr/local/bin/etcd",
        "--config-file",
        "/tmp/etcd/config/etcd.conf.yml"
      ]
    ports:
      - "23792:2379"
    environment:
      ETCDCTL_API: 3
    volumes:
      - type: bind
        source: /data/containers/etcd/s2
        target: /tmp/etcd
    networks:
      etcd-net:
        ipv4_address: ETCD_IPV4_S2

  etcd-s3:
    image: quay.io/coreos/etcd:v3.5.14
    entrypoint:
      [
        "/usr/local/bin/etcd",
        "--config-file",
        "/tmp/etcd/config/etcd.conf.yml"
      ]
    ports:
      - "23793:2379"
    environment:
      ETCDCTL_API: 3
    volumes:
      - type: bind
        source: /data/containers/etcd/s3
        target: /tmp/etcd
    networks:
      etcd-net:
        ipv4_address: ETCD_IPV4_S3

networks:
  etcd-net:
    driver: bridge
    ipam:
      config:
        - subnet: ETCD_IPV4_SUBNET
          gateway: ETCD_IPV4_GATEWAY
